print("\n========== BookifyClub - Library Management System ==========\n")
print("[1] Add a Book")
print("[2] Remove a Book")
print("[3] Manage Members")
print("[4] Borrow a Book")
print("[5] Return a Book")
print("[6] Book Recomendations")
print("[7] Community Interaction")
print("[8] Book Sharing")
print("[9] Exit\n")
print("Enter 'help' for more options or choose an action:\n")
user_input=input("Enter your choice: ")
