services:
  db:
    image: postgres
    secrets:
      - dbpassword
      - dbhost
      - dbname
    environment:
      DB_USER: adminbookifyclub
      DB_PASSWORD: /run/secrets/dbpassword
      DB_NAME: /run/secrets/dbname
      DB_HOST: /run/secrets/dbhost
    ports:
      - "5433:5432"

  app:
    build: .
    secrets:
      - dbpassword
      - dbhost
      - dbname
    environment:
      DB_HOST: /run/secrets/dbhost
      DB_USER: adminbookifyclub
      DB_NAME: /run/secrets/dbname
      DB_PASSWORD: /run/secrets/dbpassword

    ports:
      - "5005:5000"
    #depends_on:
     # db:
      #  condition: service_started

    volumes:
      - .:/app

secrets:
  dbpassword:
    file: secrets/db_password.txt
  dbhost:
    file: secrets/db_host.txt
  dbname:
    file: secrets/db_name.txt