services:
  db:
    image: postgres
    secrets:
      - dbpassword
    environment:
      DB_USER: adminbookifyclub
      DB_PASSWORD: /run/secrets/dbpassword
      DB_NAME: bookifycore
      DB_HOST: bookifyclub-db-1
    ports:
      - "5433:5432"

  app:
    build: .
    secrets:
      - dbpassword
    environment:
      DB_HOST: bookifyclub-db-1
      DB_USER: adminbookifyclub
      DB_NAME: bookifycore
      DB_PASSWORD: /run/secrets/dbpassword

    ports:
      - "5005:5000"
    #depends_on:
     # db:
      #  condition: service_started

    volumes:
      - .:/app

secrets:
  dbpassword:
    file: secrets/db_password.txt