# services:
#   db:
#     container_name: bookifyclub-db
#     image: postgres

#     environment:
#       POSTGRES_USER: adminbookifyclub
#       POSTGRES_PASSWORD: CORE
#       POSTGRES_NAME: bookifycore
#       POSTGRES_HOST: bookifyclub-db
#     ports:
#       - "5433:5432"

#   app:
#     container_name: bookifyclub-app

#     environment:
#       DB_HOST_FILE: /run/secrets/dbhost
#       DB_USER_FILE: /run/secrets/dbuser
#       DB_NAME_FILE: /run/secrets/dbname
#       DB_PASSWORD_FILE: /run/secrets/dbpassword
#       DEBUG: false


#     ports:
#       - "5005:5000"
#     depends_on:
#       db:
#         condition: service_started

#     volumes:
#       - .:/app